name: Deploy
on:
  workflow_run:
    workflows: ['Test']
    branches: [main]
    types: 
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Set up poetry
        run: pip install poetry