name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Set up poetry
        run: pip install -r requirements.txt
      - name: Cache poetry
        id: poetry
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
        if: steps.poetry.outputs.cache-hit != 'true'
      - name: Run black
        run: |
          poetry run black slackette tests --check
      - name: Run isort
        run: |
          poetry run isort slackette tests --check
      - name: Run mypy
        run: |
          poetry run mypy --strict slackette tests